### ISSUE TITLE
Changes in PackagedProductDefinition

### ISSUE THREAD

**Issue by gcangioli** [HL7/emedicinal-product-info#60]
- [x] type binding to be added (VS to be defined)
- [x] status add status value set (VS to be defined...)
- [x] to be included in legalStatusOfSupply
  - [x] code add biding (preferred)
  - [x] jurisdiction  add biding preferred
  
 - [x] PackagedProductDefinition.packaging.identifier.system modify voc biding to datacarrierIdSystem
 - [x]  type => preferred
 - [x]  rename and update the VS definition (SPOR) for:
   - [x]  VsPackageMaterialIdSystems, 
   - [x] VsShelfLifeTypeIdSystemsrename, 
   - [x] VsSpecialPrecautionsForStorageIdSystems

- [x] PackagedProductDefinition.packaging.containedItem.item just reference

**Comment by cander2** [comment]
Need help to sort out shelfLifeStorage.period[x]. Can't figure out how to bind periodDuration to VsUnitOfMeasure (i.e., time)

**Comment by cander2** [comment]
@gcangioli, can we close this one?
