### ISSUE TITLE
Changes for ClincialUseDefinition

### ISSUE THREAD

**Issue by gcangioli** [HL7/emedicinal-product-info#64]
- [ ] diseaseSymptomProcedure binding to the whole MedDra (preferred).
- [ ] itemCodeableConcept add binding to GSRS; ATC ; MedRT; 
- [ ] symptomConditionEffect	 add binding to MedDra ?
- [ ]  classification add binding value set to be defined
- [ ]  frequencyOfOccurrence WHO standard list of frequency
- [x]  warning code unconstraint

**Comment by cander2** [comment]
Need help to do these bindings

**Comment by cander2** [comment]
@gcangioli , can we close this one since it was for the ballot?
