### ISSUE TITLE
PackagedProductDefinition.name 1..1 -> 0..1

### ISSUE THREAD

**Issue by rlindstrm** [HL7/emedicinal-product-info#92]
Currently PackagedProductDefinition.name is 1..1, which is conflicting with [EMA IG](https://www.ema.europa.eu/en/documents/regulatory-procedural-guideline/product-management-services-pms-implementation-international-organization-standardization-iso_en-0.pdf) and core IDMP standard, and cause a problem for many NCAs conforming to the spec.
I propose making it optional.
[Background thread](https://chat.fhir.org/#narrow/stream/179308-BRR---Pharmacy-model/topic/HL7.20ePI.20-.20why.20PackagedProductDefinition.2Ename.201.2E.2E1.3F).

**Comment by cander2** [comment]
Changed back to optional 0..*
