### ISSUE TITLE
ManufacturedItemDefinition.identifier is mandatory

### ISSUE THREAD

**Issue by rlindstrm** [HL7/emedicinal-product-info#96]
Manufactured items do not necessarily have a business identifier, but it is made mandatory in ePI. This data element is not present in EMA IG or ISO IDMP.

However, I agree, that from a business point of view, it would be useful to have it, but unfortunately we often don't.

**Comment by cander2** [comment]
From an industry perspective they will always have at least one identifier but agree maybe better to reset to 0..* to allow process flexibility.

Updated the profile to reflect that.
