### ISSUE TITLE
PackagedProductDefinition.packaging.identifier is mandatory

### ISSUE THREAD

**Issue by rlindstrm** [HL7/emedicinal-product-info#98]
PackagedProductDefinition.**packaging**.identifier is mandatory, but it is optional in EMA IG. It is probably not available in many systems, because regulatory authorities don't normally keep track of GTINs and such. I propose making it optional.

**Comment by cander2** [comment]
The manufacturer will always have at least an internal identifier. But I see your point.

Changed back to 0..*
